name: Generate wallpapers.json

on:
  push:
    branches:
      - main
    paths:
      - 'public/blur/**'
      - 'public/car/**'
      - 'public/girl/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Generate wallpapers.json
        run: node generate-list.js

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add functions/wallpapers.json
          git commit -m "Auto update wallpapers.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
