name: Generate wallpapers.json

on:
  push:
    branches:
      - main
    paths:
      - 'public/blur/**'
      - 'public/car/**'
      - 'public/girl/**'
  workflow_dispatch:  # 支持手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate wallpapers.json
        run: |
          mkdir -p functions
          node -e "
          const fs=require('fs');const path=require('path');
          const folders=['blur','car','girl'];
          const result={};
          for(const folder of folders){
            const dir=path.join(process.cwd(),'public',folder);
            if(!fs.existsSync(dir)){result[folder]=[];continue;}
            const files=fs.readdirSync(dir).filter(f=>/\.(jpg|jpeg|png|gif|webp)$/i.test(f));
            result[folder]=files.map(f=>'/'+folder+'/'+f);
          }
          fs.writeFileSync(path.join(process.cwd(),'functions','wallpapers.json'),JSON.stringify(result,null,2));
          console.log('✅ wallpapers.json 已生成');
          "

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add functions/wallpapers.json
          git commit -m "Update wallpapers.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
